format_version: v1.0
type: UniqueComponent
attributes: {id: drv_ba414e}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BA414E_RTOS_TASK_PRIORITY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: ElementPosition
  attributes: {x: '20', y: '326', id: drv_ba414e}
